# Generated by KSC MCP Server
FROM python:3.12.12-slim

WORKDIR /app

# Install system dependencies if needed (e.g. for custom CA certs)
# RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

# Install uv for fast dependency management
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

# Copy project files
COPY pyproject.toml .
COPY README.md .
COPY packages/ packages/
COPY app/ app/

# Install dependencies using uv
# --system installs into the system python, which is fine for docker
RUN uv sync --frozen --no-cache

# Expose port (FastMCP doesn't strictly need one if using stdio, but good for potential SSE/HTTP extensions)
# EXPOSE 8000

# Run the application
# We use 'uv run' to ensure the environment is correct, though in this docker setup valid python is on path too.
CMD ["uv", "run", "ksc-mcp"]
